### ISSUE TITLE
i get error "secretOrPrivateKey 

### ISSUE THREAD

**Issue by Meguais** [becem-gharbi/nuxt-starter#10]
message
: 
"secretOrPrivateKey must have a value"
stack
: 
"<pre><span class=\"stack\">at handleError$2 (/C:/Users/Sinan/Desktop/Prisma/.nuxt/dev/index.mjs:1278:19)</span>\n<span class=\"stack\">at /C:/Users/Sinan/Desktop/Prisma/.nuxt/dev/index.mjs:1410:11</span>\n<span class=\"stack internal\">at async Object.handler (/C:/Users/Sinan/Desktop/Prisma/node_modules/h3/dist/index.mjs:1284:19)</span>\n<span class=\"stack internal\">at async Server.toNodeHandle (/C:/Users/Sinan/Desktop/Prisma/node_modules/h3/dist/index.mjs:1359:7)</span></pre>"
statusCode
: 
400
statusMessage
: 
""
url
: 
"/api/auth/login"

**Comment by Meguais** [comment]
i solved i forget jwt key
